ukvm: Refactor monitor to support multi-{arch, backend}
This change refactors the ukvm monitor to support multiple processor
architectures and hypervisor backends. It also includes preparatory work to
allow for using monitor code as a library in the future.

Changes visible to ukvm guests:

1. Guest-side APIs are now defined in ukvm_guest.h. ukvm.h has been
repurposed for monitor-side use.
2. A new, architecture-independent API for invoking hypercalls is
introduced: ukvm_do_hypercall(int UKVM_HYPERCALL_nnn, void *arg).

Internal changes:

General conventions:

1. Monitor code should use ukvm_gpa_t to represent guest physical
addresses.
2. Use of macros is discouraged as they are not type-safe.
GUEST_CHECKED_PADDR() has been rewritten appropriately as
UKVM_CHECKED_GPA_P(), the macro is used only to provide __FILE__ and
__LINE__.

Monitor source files have been reorganised as follows:

ukvm.h: Monitor APIs. Arch-independent monitor code does not need to
include any other header files.
ukvm_main.c: Main program. Arch and backend independent.
ukvm_core.c: Core functions. Maintains tables of modules, hypercall
    handlers and vmexit handlers. Implements core hypercalls (polling and
    console) which are always present. Arch and backend independent.
ukvm_elf.c: ELF loader. Arch and backend independent, will be extended
    internally to support future archs as this is just a set of #ifdefs
    around hdr.e_machine.
ukvm_cpu_{arch}.[ch]: Common arch-dependent code for backend
    implementations.
ukvm_hv_{backend}.[ch]: Arch-independent part of backend implementation.
ukvm_hv_{backend}_{arch}.[ch]: Arch-dependent part of backend
    implementation.
ukvm_module_*.c: Module implementations.

Build system changes:

ukvm-configure now accepts a UKVM_CC environment variable specifying the
compiler to use. This is intended to support cross-compilation in the
future.

To ensure that all monitor code and modules build, there is now an
ukvm/Makefile which builds a ukvm-bin with all possible modules configured.

Use as a library:

The code has been cleaned up to only export symbols prefixed with "ukvm_".
Currently all monitor APIs use the "fail fast" principle for error
handling.  For production use as a library this will need to be changed to
report (but *not* handle) errors to the top-level caller; this will be done
as a separate change later.

diff --git a/ukvm/ukvm-configure b/ukvm/ukvm-configure
--- a/ukvm/ukvm-configure
+++ b/ukvm/ukvm-configure
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 # Copyright (c) 2015-2017 Contributors as noted in the AUTHORS file
 #
 # This file is part of ukvm, a unikernel monitor.
@@ -24,41 +24,63 @@ if [ "$#" -lt 1 ]; then
     exit 1
 fi
 
+UKVM_CC=${UKVM_CC:-cc}
 UKVM_SRC=`readlink -f $1`
-if [ ! -d ${UKVM_SRC} -o ! -f ${UKVM_SRC}/ukvm-core.c ]; then
+if [ ! -d ${UKVM_SRC} -o ! -f ${UKVM_SRC}/ukvm_core.c ]; then
     echo "Error: Not a ukvm source directory: ${UKVM_SRC}" 1>&2
     exit 1
 fi
 shift
-UKVM_MODULES=$@
+
+UKVM_MODULE_OBJS=
+UKVM_MODULE_CFLAGS=
+for MODULE in "$@"; do
+    if [ ! -f ${UKVM_SRC}/ukvm_module_${MODULE}.c ]; then
+        echo "Error: Invalid module: ${MODULE}" 1>&2
+        exit 1
+    fi
+    UKVM_MODULE_OBJS="${UKVM_MODULE_OBJS} ukvm_module_${MODULE}.o"
+    UKVM_MODULE_CFLAGS="${UKVM_MODULE_CFLAGS} -DUKVM_MODULE_${MODULE}"
+done
+UKVM_MODULE_CFLAGS=$(echo ${UKVM_MODULE_CFLAGS} | tr '[a-z]' '[A-Z]')
+
+TARGET=$(${UKVM_CC} -dumpmachine)
+case ${TARGET} in
+    x86_64-*linux*)
+        UKVM_SYSDEP_OBJS="ukvm_hv_kvm.o ukvm_hv_kvm_x86_64.o ukvm_cpu_x86_64.o"
+        UKVM_SYSDEP_HEADERS="ukvm_hv_kvm.h ukvm_cpu_x86_64.h"
+        ;;
+    *)
+        echo "Error: Unsupported compiler target: ${TARGET}" 1>&2
+        echo "Error: Using compiler \"${UKVM_CC}\". Set \$UKVM_CC to change it." 1>&2
+        exit 1
+        ;;
+esac
 
 cat <<EOF> Makefile.ukvm
-# Generated by ukvm-configure $@
+# Generated by ukvm-configure "$@"
+# Using compiler "${UKVM_CC}", target "${TARGET}"
 
-UKVM_MODULE_OBJS=\$(addsuffix .o,\$(addprefix _build-ukvm/ukvm-,${UKVM_MODULES}))
-UKVM_MODULE_FLAGS=\$(addprefix -DUKVM_MODULE_,\$(shell echo ${UKVM_MODULES}| tr '[:lower:]' '[:upper:]'))
-
-UKVM_CC?=cc
-UKVM_FLAGS=-D__UKVM_HOST__ \$(UKVM_MODULE_FLAGS)
-UKVM_CFLAGS=-Wall -Werror -std=c99 -O2 -g \$(UKVM_FLAGS)
-UKVM_OBJS=_build-ukvm/ukvm-core.o \$(UKVM_MODULE_OBJS)
+UKVM_CC=${UKVM_CC}
+UKVM_CFLAGS=-Wall -Werror -std=c99 -O2 -g ${UKVM_MODULE_CFLAGS}
 ifdef UKVM_STATIC
 UKVM_LDFLAGS=-static
 endif
-UKVM_HEADERS= \\
-$UKVM_SRC/ukvm-private.h \\
-$UKVM_SRC/ukvm-modules.h \\
-$UKVM_SRC/ukvm-cpu.h \\
-$UKVM_SRC/ukvm.h
+
+UKVM_OBJS=ukvm_core.o ukvm_elf.o ukvm_main.o ${UKVM_SYSDEP_OBJS} ${UKVM_MODULE_OBJS}
+UKVM_HEADERS=ukvm.h ukvm_guest.h ukvm_cc.h ${UKVM_SYSDEP_HEADERS}
+
+UKVM_BUILD_OBJS=\$(addprefix _build-ukvm/,\$(UKVM_OBJS))
+UKVM_SRC_HEADERS=\$(addprefix ${UKVM_SRC}/,\$(UKVM_HEADERS))
 
 _build-ukvm:
 	mkdir -p _build-ukvm
 
-_build-ukvm/ukvm-%.o: $UKVM_SRC/ukvm-%.c \$(MAKEFILE_LIST) | _build-ukvm
+_build-ukvm/ukvm_%.o: ${UKVM_SRC}/ukvm_%.c \$(MAKEFILE_LIST) | _build-ukvm
 	\$(UKVM_CC) \$(UKVM_CFLAGS) -c \$< -o \$@
 
-ukvm-bin: \$(UKVM_OBJS) \$(UKVM_HEADERS) \$(MAKEFILE_LIST)
-	\$(UKVM_CC) \$(UKVM_LDFLAGS) -o \$@ \$(UKVM_CFLAGS) \$(UKVM_OBJS)
+ukvm-bin: \$(UKVM_BUILD_OBJS) \$(UKVM_SRC_HEADERS) \$(MAKEFILE_LIST)
+	\$(UKVM_CC) \$(UKVM_LDFLAGS) -o \$@ \$(UKVM_CFLAGS) \$(UKVM_BUILD_OBJS)
 
 .PHONY: ukvm-clean
 ukvm-clean:
@@ -66,4 +88,3 @@ ukvm-clean:
 	\$(RM) ukvm-bin 
 
 EOF
-
