ukvm: Add FreeBSD vmm(4) backend
Add a FreeBSD vmm(4) (a.k.a. bhyve) backend to ukvm.

The "gdb" module is not currently supported and is stubbed out when built
on FreeBSD.

Additional changes:
- ukvm-configure has been rewritten to generate a less convoluted
  Makefile.ukvm, including correct dependencies. I've also added
  user-facing documentation about its invocation.
- the code to ensure that the tap interface is pre-existing in
  tap_attach() has been simplified and ported to FreeBSD.
- the upper sleep limit in test_time has been raised somewhat to account
for behaviour on my (oldish) FreeBSD test hardware.

diff --git a/ukvm/ukvm-configure b/ukvm/ukvm-configure
--- a/ukvm/ukvm-configure
+++ b/ukvm/ukvm-configure
@@ -17,61 +17,112 @@
 # NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 # CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
+die ()
+{
+    echo "ukvm-configure: error: $@" 1>&2
+    exit 1
+}
+
 if [ "$#" -lt 1 ]; then
-    echo "Usage: ukvm-configure UKVM_SRC [MODULES]"
-    echo "    UKVM_SRC is /path/to/ukvm"
-    echo "    MODULES can be any combination of: net blk gdb"
+    cat <<EOM 1<&2
+Usage: ukvm-configure SOURCEDIR [ MODULES ... ]
+
+Configures ukvm for your target, enabling the MODULES specified.
+
+Generates a Makefile.ukvm in the current directory. Use the "ukvm-bin" target
+to build ukvm.
+
+Options:
+    SOURCEDIR is the path to the ukvm source
+    MODULES can be any combination of: net blk gdb
+
+To use a cross-compiler, set the UKVM_CC environment variable.
+To build ukvm statically, set the UKVM_STATIC environment variable.
+EOM
     exit 1
 fi
 
 UKVM_CC=${UKVM_CC:-cc}
-UKVM_SRC=`readlink -f $1`
+UKVM_SRC=$(readlink -f $1)
 if [ ! -d ${UKVM_SRC} -o ! -f ${UKVM_SRC}/ukvm_core.c ]; then
-    echo "Error: Not a ukvm source directory: ${UKVM_SRC}" 1>&2
-    exit 1
+    die "Not a ukvm source directory: ${UKVM_SRC}"
 fi
 shift
 
-UKVM_MODULE_OBJS=
-UKVM_MODULE_CFLAGS=
-for MODULE in "$@"; do
-    if [ ! -f ${UKVM_SRC}/ukvm_module_${MODULE}.c ]; then
-        echo "Error: Invalid module: ${MODULE}" 1>&2
-        exit 1
+add_cflags ()
+{
+    UKVM_CFLAGS="${UKVM_CFLAGS} $@"
+}
+
+add_obj ()
+{
+    for i in "$@"; do
+        UKVM_OBJS="${UKVM_OBJS} _build-ukvm/${i}"
+    done
+}
+
+add_header ()
+{
+    for i in "$@"; do
+        UKVM_HEADERS="${UKVM_HEADERS} ${UKVM_SRC}/${i}"
+    done
+}
+
+add_module ()
+{
+    if [ ! -f ${UKVM_SRC}/ukvm_module_$1.c ]; then
+        die "Invalid module: $1"
     fi
-    UKVM_MODULE_OBJS="${UKVM_MODULE_OBJS} ukvm_module_${MODULE}.o"
-    UKVM_MODULE_CFLAGS="${UKVM_MODULE_CFLAGS} -DUKVM_MODULE_${MODULE}"
+    enableit="-DUKVM_MODULE_$(echo $1 | tr '[a-z]' '[A-Z]')"
+    add_obj "ukvm_module_$1.o"
+    add_cflags "${enableit}"
+}
+
+UKVM_CFLAGS=
+UKVM_LDFLAGS=
+UKVM_LDLIBS=
+UKVM_HEADERS=
+UKVM_OBJS=
+add_obj ukvm_core.o ukvm_elf.o ukvm_main.o
+add_header ukvm.h ukvm_guest.h ukvm_cc.h
+
+for module in "$@"; do
+    [ -z "${module}" ] && continue
+    add_module ${module}
 done
-UKVM_MODULE_CFLAGS=$(echo ${UKVM_MODULE_CFLAGS} | tr '[a-z]' '[A-Z]')
+
+[ -n "${UKVM_STATIC}" ] && UKVM_LDFLAGS="-static"
 
 TARGET=$(${UKVM_CC} -dumpmachine)
+[ $? -ne 0 ] &&
+    die "Error running '${UKVM_CC} -dumpmachine', is your compiler working?"
 case ${TARGET} in
     x86_64-*linux*)
-        UKVM_SYSDEP_OBJS="ukvm_hv_kvm.o ukvm_hv_kvm_x86_64.o ukvm_cpu_x86_64.o"
-        UKVM_SYSDEP_HEADERS="ukvm_hv_kvm.h ukvm_cpu_x86_64.h"
+        add_obj ukvm_hv_kvm.o ukvm_hv_kvm_x86_64.o ukvm_cpu_x86_64.o
+        add_header ukvm_hv_kvm.h ukvm_cpu_x86_64.h
         ;;
+    x86_64-*freebsd1[12]*)
+        add_obj ukvm_hv_freebsd.o ukvm_hv_freebsd_x86_64.o ukvm_cpu_x86_64.o
+        add_header ukvm_hv_freebsd.h ukvm_cpu_x86_64.h
+	;;
     *)
-        echo "Error: Unsupported compiler target: ${TARGET}" 1>&2
-        echo "Error: Using compiler \"${UKVM_CC}\". Set \$UKVM_CC to change it." 1>&2
-        exit 1
+        die "Unsupported compiler target: ${TARGET}"
         ;;
 esac
 
 cat <<EOF> Makefile.ukvm
-# Generated by ukvm-configure "$@"
-# Using compiler "${UKVM_CC}", target "${TARGET}"
+# Generated by 'ukvm-configure $@'
+# Using compiler '${UKVM_CC}', target '${TARGET}'
 
 UKVM_CC=${UKVM_CC}
-UKVM_CFLAGS=-Wall -Werror -std=c99 -O2 -g ${UKVM_MODULE_CFLAGS}
-ifdef UKVM_STATIC
-UKVM_LDFLAGS=-static
-endif
+UKVM_CFLAGS=-Wall -Werror -std=c99 -O2 -g ${UKVM_CFLAGS}
+UKVM_LDFLAGS=${UKVM_LDFLAGS}
+UKVM_LDLIBS=${UKVM_LDLIBS}
 
-UKVM_OBJS=ukvm_core.o ukvm_elf.o ukvm_main.o ${UKVM_SYSDEP_OBJS} ${UKVM_MODULE_OBJS}
-UKVM_HEADERS=ukvm.h ukvm_guest.h ukvm_cc.h ${UKVM_SYSDEP_HEADERS}
+UKVM_OBJS=${UKVM_OBJS}
+UKVM_HEADERS=${UKVM_HEADERS}
 
-UKVM_BUILD_OBJS=\$(addprefix _build-ukvm/,\$(UKVM_OBJS))
-UKVM_SRC_HEADERS=\$(addprefix ${UKVM_SRC}/,\$(UKVM_HEADERS))
+\$(UKVM_OBJS): \$(UKVM_HEADERS)
 
 _build-ukvm:
 	mkdir -p _build-ukvm
@@ -79,12 +130,11 @@ _build-ukvm:
 _build-ukvm/ukvm_%.o: ${UKVM_SRC}/ukvm_%.c \$(MAKEFILE_LIST) | _build-ukvm
 	\$(UKVM_CC) \$(UKVM_CFLAGS) -c \$< -o \$@
 
-ukvm-bin: \$(UKVM_BUILD_OBJS) \$(UKVM_SRC_HEADERS) \$(MAKEFILE_LIST)
-	\$(UKVM_CC) \$(UKVM_LDFLAGS) -o \$@ \$(UKVM_CFLAGS) \$(UKVM_BUILD_OBJS)
+ukvm-bin: \$(UKVM_OBJS) \$(MAKEFILE_LIST)
+	\$(UKVM_CC) \$(UKVM_LDFLAGS) -o \$@ \$(UKVM_OBJS) \$(UKVM_LDLIBS)
 
 .PHONY: ukvm-clean
 ukvm-clean:
 	\$(RM) -r _build-ukvm
-	\$(RM) ukvm-bin 
-
+	\$(RM) ukvm-bin
 EOF
